# Generated by Django 4.2.23 on 2025-10-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paneladmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=15, verbose_name='Estado')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paneladmin.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'unique_together': {('medico', 'fecha')},
            },
        ),
    ]
