# Generated by Django 4.2.23 on 2025-10-23 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paneladmin', '0002_cita_disponibilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('medico', 'fecha_hora')},
        ),
    ]
