# Generated by Django 4.2.23 on 2025-10-23 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paneladmin', '0003_alter_cita_options_alter_cita_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora Bloqueada')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Bloqueado',
                'verbose_name_plural': 'Horarios Bloqueados',
                'unique_together': {('medico', 'fecha_hora')},
            },
        ),
    ]
