# Generated by Django 4.2.23 on 2025-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneladmin', '0004_horariobloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la consulta'),
        ),
    ]
