# Generated by Django 4.2.23 on 2025-10-29 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_last_failed_login_usuario_login_attempts'),
        ('paneladmin', '0006_receta_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_medica', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('altura_cm', models.PositiveIntegerField(blank=True, help_text='Altura en centímetros.', null=True, verbose_name='Altura (cm)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos.', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'No sabe')], max_length=3, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, help_text='Listar alergias a medicamentos, alimentos, etc.', verbose_name='Alergias conocidas')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Listar condiciones médicas preexistentes.', verbose_name='Enfermedades Crónicas')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
