# Generated by Django 4.2.23 on 2025-10-23 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('email', models.EmailField(help_text='El correo electrónico se usará para iniciar sesión.', max_length=254, unique=True, verbose_name='correo electrónico')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='número de teléfono')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=10, verbose_name='rol')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='foto de perfil')),
                ('antecedentes_medicos', models.FileField(blank=True, null=True, upload_to='antecedentes/', verbose_name='antecedentes médicos')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa si el usuario puede iniciar sesión en el panel de administración.', verbose_name='es administrador')),
                ('is_active', models.BooleanField(default=True, help_text='Designa si este usuario debe ser tratado como activo. Desmárcalo en lugar de eliminar la cuenta.', verbose_name='está activo')),
                ('date_joined', models.DateField(db_column='fecha_registro', default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
