# Generated by Django 4.2.23 on 2025-10-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneladmin', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Asignar solo si el rol es Médico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paneladmin.especialidad', verbose_name='especialidad'),
        ),
    ]
