# Generated by Django 4.2.23 on 2025-10-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último intento fallido.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='login_attempts',
            field=models.IntegerField(default=0, help_text='Contador de intentos de login fallidos.'),
        ),
    ]
